server:
  port: 8050
  tomcat:
    max-http-post-size: 1048576000
eureka:
  client:
    servieUrl:
      defaultZone: http://user:password123@localhost:8761/eureka/
  instance:
    perefer-ip-address: true
spring:
  application:
    name: microservice-file-upload
  http:
    multipart:
      max-file-size: 2000Mb #Max file size 默认1M
      max-request-size: 2500Mb # 默认10M

