spring:
  application:
    name: microservice-discovery-eureka-ha
---
spring:
  #指定profile=peer1
  profiles: peer1
server:
  port: 8761
eureka:
  instance:
    #指定当profile=peer1，主机名是peer1
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://peer2:8762/eureka/
---
spring:
  #指定profile=peer1
  profiles: peer2
server:
  port: 8762
eureka:
  instance:
    #指定当profile=peer1，主机名是peer1
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/