spring:
  application:
    name: microservice-profile-movie-understanding-metadata
server:
  port: 8010
eureka:
  client:
    servieUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    perefer-ip-address: true
