server:
  port: 8010
spring:
  application:
    name: microservice-consumer-movie-feign-logging

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
logging:
  level:
    com.hysky.cloud.user.feign.UserFeignClient: DEBUG #将Feign接口的日志级别设置成DEBUG，因为Feign的Logger.Level只对Debug做出响应
